In [1]:
#load dependencies
from matplotlib import pyplot as plt
from scipy.stats import linregress
from pprint import pprint
import pandas as pd

In [2]:
pop_df=pd.read_csv('Resources/Census_Pop_2019.csv')
pop_df.head(20)

                    State 2019 Population
0                .Alabama       4,903,185
1                 .Alaska         731,545
2                .Arizona       7,278,717
3               .Arkansas       3,017,804
4             .California      39,512,223
5               .Colorado       5,758,736
6            .Connecticut       3,565,287
7               .Delaware         973,764
8   .District of Columbia         705,749
9                .Florida      21,477,737
10               .Georgia      10,617,423
11                .Hawaii       1,415,872
12                 .Idaho       1,787,065
13              .Illinois      12,671,821
14               .Indiana       6,732,219
15                  .Iowa       3,155,070
16                .Kansas       2,913,314
17              .Kentucky       4,467,673
18             .Louisiana       4,648,794
19                 .Maine       1,344,212